config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "chat/enter_name", to: "chat#enter_name", as: :chat_enter_name
  get "chat/enter_in_room", to: "chat#enter_in_room", as: :chat_enter_in_room
  get "chats", to: "chat#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  before_action :authenticate_user!

  def index
    @email = current_user.email
  end

  def start_public_chat

  end

  def start_private_chat

  end

  # get /single-channel
  def room
    redirect_to(action: 'enter_name') if cookies.encrypted[:user_name].blank?
  end

  def enter_name
    redirect_to(action: 'room') if cookies.encrypted[:user_name].present?
  end

  def enter_in_room
    redirect_to(action: 'room') if cookies.encrypted[:user_name].present?

    redirect_to(action: 'enter_name') if params[:name].blank?

    cookies.encrypted[:user_name] = params[:name]

    redirect_to(action: 'room')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chat/enter_name.html.erb
<%# <%= javascript_pack_tag 'hello_world_channel' %> %>

<h1 class="bg-blue-200 text-blue-700 text-2xl pt-8">Hello</h1>
<%= form_with url: chat_enter_in_room_path, class: "flex flex-col w-full items-center py-32 px-4", method: :get do |form| %>
  <div class="text-gray-800 text-xl">
    Enter Your Name
  </div>

  <%= form.text_field :name, class: "w-64 border border-gray-200 p-2 m-4", placeholder: "Name", required: true %>
  <%= form.submit "Enter in chat room", class: "bg-green-400 hover:bg-green-700 rounded-full px-5 py-3 text-white text-lg font-bold" %>
<% end %>

<div class="m-4 bg-gray-50 rounded" div-for="channel-data-recevied">

app/views/chat/index.html.erb
<style>
.active-room {
  display: block;
}

.disabled-room {
  display: hidden;
}
</style>
<div data-controller="chat-room" data-chat-room-email="<%= @email %>" data-chat-room-active-room-id="" class="flex flex-row h-screen">
  <div data-chat-room-target="list" class="flex flex-col w-96 bg-gray-50 border-r border-gray-200">
    <div id="start_chat_room_public" data-action="click->chat-room#startChatRoom" data-room-name="public" data-room-title="Public" class="w-full px-3 py-4">
      <div data-room-name="public" data-room-title="Public">Public</div>
      <div data-room-name="public" data-room-title="Public" class="text-sm text-gray-500">Click to start chat</div>
    </div>
    <div id="show_chat_room_public" data-action="click->chat-room#showChatRoom" data-room-name="public" class="w-full px-3 py-4" style="display: none;">
      <div data-room-name="public">Public</div>
    </div>
    <% User.all.each do |user| %>
      <% room_name = [@email, user.email].sort.join('_') %>
      <div id="start_chat_room_<%=room_name%>" data-action="click->chat-room#startChatRoom" data-room-name="<%=room_name%>" class="w-full px-3 py-4">
        <div data-room-name="<%=room_name%>" data-room-title="<%=user.email%>"><%=user.email%> <%= user == current_user ? " (You)" : "" %></div>
        <div data-room-name="<%=room_name%>" data-room-title="<%=user.email%>" class="text-sm text-gray-500">Click to start chat</div>
      </div>
      <div id="show_chat_room_<%=room_name%>" data-action="click->chat-room#showChatRoom " data-room-name="<%=room_name%>" class="w-full px-3 py-4" style="display: none;">
        <div data-room-name="<%=room_name%>"><%=user.email%> <%= user == current_user ? " (You)" : "" %></div>
      </div>
    <% end %>
  </div>

  <div id="rooms" class="w-full">
  </div>


</div> <%# <div data-controller="chat-room"> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoActioncable</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tailwindcss/2.0.3/tailwind.min.css" integrity="sha512-wl80ucxCRpLkfaCnbM88y4AxnutbGk327762eM9E/rRTvY/ZGAHWMZrYUq66VQBYMIYDFpDdJAOGSLyIPHZ2IQ==" crossorigin="anonymous" />

  </head>

  <body>
    <%= yield %>
  </body>
</html>